### ISSUE TITLE
compatibility with loaders-modernized

### ISSUE THREAD

**Issue by gralewski** [Jobus0/Factorio-MultiplierMods#1]
this should fix the problem of speeds not updated for these loaders

data-final-fixes.lua - add this to the code

```lua
if (mods["loaders-modernized"]) then
    local type = data.raw['loader-1x1']

    for _, prot in pairs(type) do
        prot.speed = prot.speed*multiplier
    end
end
```

**Comment by Jobus0** [comment]
Thank you for pointing out this issue.

I didn't realize loader-1x1 is actually part of the official API even though it is a mod-only type, so there's no reason to filter by mods at all. I'll update the mod so it should support all loader mods and also [lane balancers](https://mods.factorio.com/mod/lane-balancers).

**Comment by Jobus0** [comment]
Mod has been updated. All belt mods that build on top of the official API's types should be supported now. I also checked and confirmed that loaders-modernized works.

**Comment by gralewski** [comment]
Thanks!
